apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-chart-source
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  ref:
    tag: 0.1514.1
  url: oci://ghcr.io/zk2sk2/helm-cp-cfk/confluent-for-kubernetes
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${releaseName}
  namespace: ${releaseNamespace}
spec:
  interval: 15s
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-chart-source
    namespace: ${releaseNamespace}
  targetNamespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
